name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    env: 
      CIVICRM_VERSION: 5.19
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Test dir
      run: | 
        mkdir build
        git clone -b $CIVICRM_VERSION --depth 1 https://github.com/compucorp/civicrm-core.git build/civicrm-core

    - name: Run test
      uses: ./
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        repo: 'compucorp/civicrm-core'
        version: ${{ env.CIVICRM_VERSION }}
        path: 'build/civicrm-core'

