name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Test dir
      run: | 
        mkdir build
        git clone -b 5.24.0 --depth 1 https://github.com/erawat/civicrm-core.git build/civicrm-core

    - name: Run test
      uses: ./
      working-directory: 'build/civicrm-core' 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        owner: 'erawat'
        repo: 'civicrm:civicrm-core'
        base: '5.24.6'
        head: 5.24.6-patches 
    
    - name: Test if a patch is applied
      working-directory: 'build/civicrm-core' 
      run: |
        cat github/workflows/patch.yml
        cat CRM/ACL/BAO/ACL.php 
          

