name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master

jobs:

  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: ./
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        owner: 'civicrm'
        repo: 'civicrm-core'
        base: 'master'
