name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  # test action works running from workflow  
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: erawat/apply-patches@master
    - uses: ./
      with:
        owner: 'compucorp'
        repo: 'civicrm-core'
        branch: '5.19.4-patches'
