name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Test dir
      run: | 
        mkdir build
        git clone -b 5.19 --depth 1 https://github.com/compucorp/civicrm-core.git build/civicrm-core

    - name: Run test
      uses: ./
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        owner: 'erawat'
        repo: 'civicrm-core'
        base: '5.19'
        head: '5.19' 
        path: 'build/civicrm-core' 
