name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build CiviCRM profile
      run: | 
        mkdir build
        git clone https://github.com/civicrm/civicrm-core.git build/civicrm-core
    
    - uses: ./
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        owner: 'erawat'
        repo: 'civicrm-core'
        base: '5.24.6-patches'
        to_patch_dir: 'build/civicrm-core' 
