name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Run test
      uses: ./
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        owner: 'erawat'
        repo: 'civicrm-core'
        baseHead: '5.24.6'
        patchesBranch: 5.24.6-patches 
        state: 'closed'
        to_patch_dir: 'build/civicrm-core' 

