name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build CiviCRM profile
      run: | 
        mkdir build
        git clone -b 5.24.0 --depth 1 https://github.com/civicrm/civicrm-core.git build/civicrm-core
        cd build/civicrm-core
        cat CRM/ACL/BAO/Cache.php
    
    - name: Run test
      uses: ./
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        owner: 'erawat'
        repo: 'civicrm-core'
        base: '5.25.0-patches'
        state: 'closed'
        to_patch_dir: 'build/civicrm-core' 

    - name: Build CiviCRM profile
      run: |    
        cd build/civicrm-core
        cat CRM/ACL/BAO/Cache.php
